# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 09:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CastingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка на фотографию')),
                ('rating', models.IntegerField(db_index=True, default=0, verbose_name='Рейтинг фотографии')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Количество проголосовавших')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь-участник')),
            ],
            options={
                'verbose_name_plural': 'Участники голосования',
                'verbose_name': 'Участник голосования',
                'db_table': 'casting_user',
            },
        ),
    ]
